AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'user-lambda

  Sample SAM Template for user-lambda

  '
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://user-lambda/8ab159890ad262d0f65bd3b887dd70cb
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            Fn::GetAtt:
            - UserSNS
            - TopicName
  UserSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: UserSNS
      TopicName: UserSNSTopic
  UserSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: UserQueue
  userQueueToSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Fn::GetAtt:
        - UserSQS
        - Arn
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn:
        Ref: UserSNS
  queueInvokesLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://user-lambda/688aadcf9fcb6553f67da85a0dc6de70
      Handler: app.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          MY_SQS_QUEUE_URL:
            Ref: UserSQS
      Events:
        SqsJobQueue:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - UserSQS
              - Arn
            BatchSize: 1
  userQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: UserSQS
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:*
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: UserSNS
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionRole
      - Arn
  UserSNS:
    Description: SNS Topic for User Events
    Value:
      Ref: UserSNS
